[package]
name = "euc"
version = "0.1.0"
description = "A software rendering crate that lets you write shaders with Rust"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
license = "Apache-2.0 AND MIT"
repository = "https://github.com/zesterer/euc"
readme = "README.md"
edition = "2018"
keywords = ["renderer", "3D", "graphics", "raster"]
exclude = ["misc"]

[dependencies]
vek = "0.9"

[dev-dependencies]
minifb = "0.11"
tobj = "0.1"

[features]
nightly = []
