[package]
name = "euc"
version = "0.1.0"
description = "A software rendering crate that lets you write shaders with Rust"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2018"

[features]
no_std = []

[dependencies]
vek = "0.9"

[dev-dependencies]
minifb = "0.11"
tobj = "0.1"
